# Generated by Django 4.2.23 on 2025-09-01 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de publicación"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("content", models.TextField(verbose_name="Comentario")),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["created_date"],
            },
        ),
    ]
